version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

 
  primarybackend:
    build:
      context: ./primarybackend
    container_name: primarybackend
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: AutomateXFrontend
    ports:
      - "3001:3001"
    depends_on:
      - primarybackend
    environment:
      - NEXT_PUBLIC_PRIMARY_BACKEND=http://localhost:3000

  hooks:
    build:
      context: ./hooks
    container_name: hooks
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
    depends_on:
      - db
      - primarybackend


  # processor:
  #   build:
  #     context: ./processor
  #   container_name: processor
  #   environment:
  #     - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
  #     - kafka_broker=automatexkafka:9092
  #     - kafka_topic="zap-events"
  #   depends_on:
  #     - db
  #     - automatexkafka

  # worker:
  #   build:
  #     context: ./worker
  #   container_name: worker
  #   environment:
  #     - NDOEMAILER_PASSWORD="cafl yqqr rsjh lcty"
  #     - NDOEMAILER_USERNAME="zapierautomationservice@gmail.com"
  #     - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydb
  #     - kafka_broker=automatexkafka:9092
  #     - kafka_topic="zap-events"
  #   depends_on:
  #     - db
  #     - automatexkafka  
  #     - processor
  #     - primarybackend

volumes:
  postgres_data:


